apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: owncast
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: owncast
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: owncast
    app.kubernetes.io/version: 0.0.7
    helm.sh/chart: owncast-3.4.2
  name: owncast
  namespace: default
spec:
  ports:
    - name: rtmp
      port: 1935
      protocol: TCP
      targetPort: 1935
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: owncast
    app.kubernetes.io/name: owncast


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
  generation: 1
  name: owncast-rtmp-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: owncast-rtmp
      port:
        number: 1935

---

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gce
  generation: 1
  name: owncast-ingress
  namespace: default
spec:
  defaultBackend:
    service:
      name: owncast
      port:
        number: 8080